openapi: 3.0.0
info:
  title: Crypto API
  version: 1.0.0
  description: API for searching and retrieving cryptocurrency data using CoinGecko.

servers:
  - url: http://localhost:3000

paths:
  /:
    get:
      summary: Get paginated market data for coins
      description: Returns a paginated list of coins with market data in the selected currency.
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
          description: Page number for pagination.
        - name: per_page
          in: query
          schema:
            type: integer
            default: 50
          description: Number of coins per page (max 250).
        - name: vs_currency
          in: query
          schema:
            type: string
            default: brl
            enum: [usd, brl]
          description: The currency to return the price in (default: brl).
      responses:
        '200':
          description: A list of coins with market data.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MarketCoin'
        '500':
          $ref: '#/components/responses/InternalError'

  /search:
    get:
      summary: Search for coins by name or symbol
      description: Returns metadata about coins that match the search query. Does NOT return price or market data.
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
          description: The search term to look for (e.g., coin name or symbol)
      responses:
        '200':
          description: List of coins and related entities matching the search query
          content:
            application/json:
              schema:
                type: object
                properties:
                  coins:
                    type: array
                    items:
                      $ref: '#/components/schemas/SearchCoin'
                  exchanges:
                    type: array
                    items:
                      type: object
                  icos:
                    type: array
                    items:
                      type: object
                  categories:
                    type: array
                    items:
                      type: object
                  nfts:
                    type: array
                    items:
                      type: object
        '500':
          $ref: '#/components/responses/InternalError'

  /total:
    get:
      summary: Get total number of coins
      description: Returns the total number of available coins and a list of their basic info.
      responses:
        '200':
          description: Total number of coins and their basic info.
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  coins:
                    type: array
                    items:
                      $ref: '#/components/schemas/BasicCoin'
        '500':
          $ref: '#/components/responses/InternalError'

  /coin:
    get:
      summary: Get detailed info for a specific coin (query parameter)
      description: Returns detailed information for a specific coin, including price in a given currency.
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
          description: The CoinGecko coin ID.
        - name: currency
          in: query
          schema:
            type: string
            default: usd
            enum: [usd, brl]
          description: The currency to return the price in (default: usd).
      responses:
        '200':
          description: Detailed info for the requested coin.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoinDetail'
        '400':
          description: No coin provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          $ref: '#/components/responses/InternalError'

  /coin/{id}:
    get:
      summary: Get detailed info for a specific coin (path parameter)
      description: Returns detailed information for a specific coin by its CoinGecko ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The CoinGecko coin ID.
      responses:
        '200':
          description: Detailed info for the requested coin.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoinDetail'
        '400':
          description: No coin provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          $ref: '#/components/responses/InternalError'

components:
  responses:
    InternalError:
      description: Server error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string

  schemas:
    MarketCoin:
      type: object
      properties:
        id:
          type: string
        symbol:
          type: string
        name:
          type: string
        image:
          type: string
        current_price:
          type: number
        market_cap:
          type: number
        market_cap_rank:
          type: integer
        total_volume:
          type: number
        high_24h:
          type: number
        low_24h:
          type: number
        price_change_24h:
          type: number
        price_change_percentage_24h:
          type: number
        sparkline_in_7d:
          type: object
          properties:
            price:
              type: array
              items:
                type: number
        price_change_percentage_1h_in_currency:
          type: number
        price_change_percentage_24h_in_currency:
          type: number
        price_change_percentage_7d_in_currency:
          type: number

    BasicCoin:
      type: object
      properties:
        id:
          type: string
        symbol:
          type: string
        name:
          type: string

    SearchCoin:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        api_symbol:
          type: string
        symbol:
          type: string
        market_cap_rank:
          type: integer
        thumb:
          type: string
        large:
          type: string

    CoinDetail:
      type: object
      properties:
        id:
          type: string
        symbol:
          type: string
        name:
          type: string
        market_data:
          type: object
          properties:
            current_price:
              type: object
              properties:
                usd:
                  type: number
                brl:
                  type: number